name: Pull Request Checker

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Validate
        shell: bash
        run: |
          set -e

          dart pub get
          dart format --set-exit-if-changed lib test
          dart run build_runner build
          dart analyze
          dart test

      - name: Compile Binary
        run: |
          dart compile exe bin/detect_changes.dart -o bin/detect_changes
          dart compile exe bin/pubspec_tag.dart -o bin/pubspec_tag
          dart compile exe bin/scan_pubspec.dart -o bin/scan_pubspec
          dart compile exe bin/update_repo_properties.dart -o bin/update_repo_properties
          echo "bin" >> $GITHUB_PATH

      - uses: islandlifetechnologies/markup@v1

      - name: Update README.md
        shell: bash
        run: |
          markup -i README.md
