name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [bin]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: islandlifetechnologies/gh_tools@v1

      - name: detect_changes
        shell: bash
        run: |
          detect_changes --help

      - name: pubspec_tag
        shell: bash
        run: |
          pubspec_tag --help

      - name: scan_pubspec
        shell: bash
        run: |
          scan_pubspec --help

      - name: update_repo_properties
        shell: bash
        run: |
          update_repo_properties --help

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: islandlifetechnologies/gh_tools@v1

      - name: detect_changes
        shell: bash
        run: |
          detect_changes --help

      - name: pubspec_tag
        shell: bash
        run: |
          pubspec_tag --help

      - name: scan_pubspec
        shell: bash
        run: |
          scan_pubspec --help

      - name: update_repo_properties
        shell: bash
        run: |
          update_repo_properties --help

  test-windows:
    runs-on: windows-latest

    steps:
      - uses: islandlifetechnologies/gh_tools@v1

      - name: detect_changes
        shell: bash
        run: |
          detect_changes --help

      - name: pubspec_tag
        shell: bash
        run: |
          pubspec_tag --help

      - name: scan_pubspec
        shell: bash
        run: |
          scan_pubspec --help

      - name: update_repo_properties
        shell: bash
        run: |
          update_repo_properties --help
